export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const LOAD_ALL_PRODUCT = 'LOAD_ALL_PRODUCT';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCT_DETAIL_SUCCESS = 'LOAD_PRODUCT_DETAIL_SUCCESS';
